# Useful utils
$scripts = $HOME/.config/hypr/scripts

# Fav programs
# reset submap if an app is selected
$menu = rofi -show combi -modes "combi,Actions:$HOME/.config/hypr/scripts/actions.sh,Emoji:$HOME/.config/hypr/scripts/emoji.sh"
$terminal = kitty
$code = kitty --class nvim nvim # custom class so it can be matched
$fileManager = thunar
$browser = zen-browser
$mail = thunderbird

# for keybinds.conf
$mainMod = SUPER

